### user signup
POST http://localhost:8000/users
Content-Type: application/json

{
  "username": "bbb",
  "email": "bbb@gmail.com",
  "password": "bbb"
}

### user login / get token
POST http://localhost:8000/token
Content-Type: multipart/form-data; boundary=FormBoundary
Accept: application/json

--FormBoundary
Content-Disposition: form-data; name="username"

bbb
--FormBoundary
Content-Disposition: form-data; name="password"

bbb
--FormBoundary--

### create a post for a user
POST http://localhost:8000/posts/
Content-Type: application/json
Authorization: Bearer // insert token here

{
"content": "new post for user 2"
}

### get all posts
GET http://localhost:8000/posts/
Accept: application/json
Authorization: Bearer // insert token here

### get my posts
GET http://localhost:8000/posts/mine/
Accept: application/json
Authorization: Bearer // insert token here

### add likes to a post
PATCH http://localhost:8000/posts/2/like/
Content-Type: application/json
Authorization: Bearer // insert token here

### add dislikes to a post
PATCH http://localhost:8000/posts/2/dislike/
Content-Type: application/json
Authorization: Bearer // insert token here
